import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { MasterParsedPayload } from "@/lib/types";

type ReportDoc = jsPDF & {
  lastAutoTable?: {
    finalY: number;
  };
};

function getTickerColor(ticker: string): [number, number, number] {
  const t = ticker.toUpperCase();
  if (t.includes("ABSL")) return [99, 91, 255]; // Indigo
  if (t.includes("TRANS")) return [14, 165, 233]; // Sky
  if (t.includes("GREEN")) return [16, 185, 129]; // Emerald
  if (t.includes("PORTS")) return [245, 158, 11]; // Amber
  if (t.includes("AMARA")) return [107, 114, 128]; // Gray
  return [99, 91, 255]; // Default Indigo
}

export async function exportPortfolioReport(
  session: MasterParsedPayload
): Promise<void> {
  // A4 dimensions: 210mm x 297mm
  const doc = new jsPDF("p", "mm", "a4") as ReportDoc;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const indigoRGB: [number, number, number] = [99, 91, 255];
  const darkRGB: [number, number, number] = [10, 37, 64];
  const grayRGB: [number, number, number] = [100, 116, 139];

  // Helper to draw consistent top header bar and page footer on every page
  const drawHeaderAndFooter = (pageNum: number) => {
    // Top header bar (Indigo, full width, 15mm height)
    doc.setFillColor(...indigoRGB);
    doc.rect(0, 0, pageWidth, 15, "F");

    // Title left
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Rapidash Portfolio Report", 12, 9.5);

    // Date right
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    const dateStr = new Date().toLocaleDateString("en-IN");
    doc.text(`Date: ${dateStr}`, pageWidth - 12, 9.5, { align: "right" });

    // Footer divider line
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.2);
    doc.line(12, pageHeight - 15, pageWidth - 12, pageHeight - 15);

    // Footer text and page counts
    doc.setFontSize(7);
    doc.setTextColor(...grayRGB);
    doc.text(
      "Generated by Rapidash - Privacy-first wealth tracking. Personal report for CA / Financial Advisor review. Not financial advice.",
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
    doc.text(`Page ${pageNum} of 3`, pageWidth - 12, pageHeight - 10, { align: "right" });
  };

  // ==========================================
  // PAGE 1 — SUMMARY
  // ==========================================
  drawHeaderAndFooter(1);

  // Portfolio total value calculation
  const holdingsValue = session.holdings.reduce(
    (sum, holding) => sum + holding.current_market_value,
    0
  );
  const totalValue = holdingsValue + session.ledger_summary.closing_cash_balance;

  // Portfolio summary box (Subtle gray border box, Y: 22 to 48)
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.setFillColor(252, 253, 255);
  doc.roundedRect(12, 22, pageWidth - 24, 26, 2, 2, "FD");

  // Total Value metrics label & large bold text
  doc.setTextColor(...grayRGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.text("TOTAL PORTFOLIO VALUE", 16, 28);

  doc.setTextColor(...indigoRGB);
  doc.setFontSize(16);
  doc.text(
    `Rs. ${totalValue.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    16,
    35
  );

  // Metadata information row: Date | Broker | Health Score
  doc.setTextColor(...grayRGB);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  const metadataRow = `Statement Date: ${session.metadata.statement_timestamp}    |    Broker: ${session.metadata.origin_broker}    |    Health Score: ${session.health_score ? `${session.health_score.score}/100` : "N/A"}`;
  doc.text(metadataRow, 16, 42.5);

  // Holdings allocation visual section (Y: 54 onwards)
  doc.setTextColor(...darkRGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Portfolio Allocation", 12, 58);

  // Gather allocation items (Holdings + Cash)
  const allocationItems = session.holdings.map((h) => ({
    name: h.ticker_symbol,
    value: h.current_market_value,
    color: getTickerColor(h.ticker_symbol),
  }));

  if (session.ledger_summary.closing_cash_balance > 0) {
    allocationItems.push({
      name: "Cash Balance",
      value: session.ledger_summary.closing_cash_balance,
      color: [107, 114, 128] as [number, number, number],
    });
  }

  // Sort by asset valuation descending
  allocationItems.sort((a, b) => b.value - a.value);

  // Draw horizontal bars for each allocation item
  let currentY = 64;
  allocationItems.forEach((item) => {
    const pct = totalValue > 0 ? item.value / totalValue : 0;
    const barMaxWidth = 110; // max width in mm
    const barWidth = pct * barMaxWidth;

    // Draw background track (light gray)
    doc.setFillColor(241, 245, 249);
    doc.rect(12, currentY, barMaxWidth, 4, "F");

    // Draw colored progress fill
    doc.setFillColor(...item.color);
    doc.rect(12, currentY, Math.max(1, barWidth), 4, "F");

    // Draw text stats on the right side of the bar
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    const itemPctStr = `${(pct * 100).toFixed(1)}%`;
    const labelStr = `${item.name}   Rs. ${item.value.toLocaleString("en-IN", { maximumFractionDigits: 0 })}   (${itemPctStr})`;
    doc.text(labelStr, 126, currentY + 3.2);

    currentY += 7.2; // height 4mm + gap 3.2mm
  });

  // AI Advisor Memo Box at the bottom of Page 1
  const memoY = pageHeight - 55;
  doc.setFillColor(250, 250, 252);
  doc.setDrawColor(230, 235, 245);
  doc.setLineWidth(0.3);
  doc.roundedRect(12, memoY, pageWidth - 24, 30, 2, 2, "FD");

  doc.setTextColor(...indigoRGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("AI ADVISOR MEMO", 16, memoY + 6);

  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  const memoText = session.investment_memo
    ? session.investment_memo.trim()
    : "No advisor notes generated for this statement. Please review holdings and rebalancing recommendations.";

  const textLines = doc.splitTextToSize(memoText, pageWidth - 32) as string[];
  const memoLines = textLines.slice(0, 5);
  let lineY = memoY + 11.5;
  memoLines.forEach((line) => {
    doc.text(line, 16, lineY);
    lineY += 3.6;
  });

  // ==========================================
  // PAGE 2 — HOLDINGS TABLE
  // ==========================================
  doc.addPage();
  drawHeaderAndFooter(2);

  doc.setTextColor(...darkRGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Asset Allocation Ledger", 12, 23);

  // Prepare table body columns: Ticker | ISIN | Quantity | Value | Allocation%
  const holdingsTableBody: (string | number)[][] = [];
  session.holdings.forEach((h) => {
    const sharePct = totalValue > 0 ? (h.current_market_value / totalValue) * 100 : 0;
    holdingsTableBody.push([
      h.ticker_symbol,
      h.isin,
      h.quantity.toLocaleString("en-IN"),
      `Rs. ${h.current_market_value.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `${sharePct.toFixed(1)}%`,
    ]);
  });

  if (session.ledger_summary.closing_cash_balance > 0) {
    const cashPct = totalValue > 0 ? (session.ledger_summary.closing_cash_balance / totalValue) * 100 : 0;
    holdingsTableBody.push([
      "Cash Balance",
      "-",
      "-",
      `Rs. ${session.ledger_summary.closing_cash_balance.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `${cashPct.toFixed(1)}%`,
    ]);
  }

  // Draw holdings autoTable
  autoTable(doc, {
    startY: 27,
    head: [["Ticker", "ISIN", "Quantity", "Current Value", "Allocation %"]],
    body: holdingsTableBody,
    headStyles: { fillColor: indigoRGB, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 255] },
    styles: { fontSize: 8, cellPadding: 2.8, font: "helvetica" },
    margin: { left: 12, right: 12 },
  });

  // ==========================================
  // PAGE 3 — ADVISORY
  // ==========================================
  doc.addPage();
  drawHeaderAndFooter(3);

  doc.setTextColor(...darkRGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Smart Rebalancing Analysis", 12, 23);

  // Suggestion rows with action-colored columns
  const rebalanceTableBody: (string | number)[][] = [];
  if (session.rebalancing) {
    session.rebalancing.suggestions.forEach((s) => {
      rebalanceTableBody.push([
        s.category,
        `Rs. ${s.current_value.toLocaleString("en-IN")}`,
        `Rs. ${s.ideal_value.toLocaleString("en-IN")}`,
        s.action.toUpperCase(),
        `Rs. ${Math.abs(s.difference).toLocaleString("en-IN")}`,
      ]);
    });
  }

  autoTable(doc, {
    startY: 27,
    head: [["Category", "Current Value", "Ideal Target Value", "Action", "Difference"]],
    body: rebalanceTableBody,
    headStyles: { fillColor: indigoRGB, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 255] },
    styles: { fontSize: 8, cellPadding: 2.8, font: "helvetica" },
    margin: { left: 12, right: 12 },
    didParseCell: (data) => {
      // Color action cells in column 3 (index 3) dynamically
      if (data.row.section === "body" && data.column.index === 3) {
        const actionStr = String(data.cell.raw || "").toLowerCase();
        if (actionStr.includes("buy")) {
          data.cell.styles.fillColor = [220, 252, 231]; // light green #dcfce7
          data.cell.styles.textColor = [22, 163, 74]; // green #16a34a
        } else if (actionStr.includes("sell")) {
          data.cell.styles.fillColor = [254, 226, 226]; // light red #fee2e2
          data.cell.styles.textColor = [220, 38, 38]; // red #dc2626
        } else if (actionStr.includes("hold")) {
          data.cell.styles.fillColor = [241, 245, 249]; // gray #f1f5f9
          data.cell.styles.textColor = [100, 116, 139]; // gray #64748b
        }
      }
    },
  });

  const nextTableStartY = (doc.lastAutoTable?.finalY ?? 130) + 12;

  doc.setTextColor(...darkRGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Monthly SIP Recommendation Targets", 12, nextTableStartY - 4);

  // SIP targets table
  const sipTableBody: (string | number)[][] = [];
  if (session.sip_plan) {
    session.sip_plan.allocations.forEach((a) => {
      sipTableBody.push([
        a.fund_name,
        a.fund_category,
        `Rs. ${a.monthly_amount.toLocaleString("en-IN")}/mo`,
        `${a.months_to_target} months`,
        a.action_label,
      ]);
    });
  }

  autoTable(doc, {
    startY: nextTableStartY,
    head: [["Recommended Target Fund", "Category", "Monthly Amount", "Timeline", "Action Target"]],
    body: sipTableBody,
    headStyles: { fillColor: indigoRGB, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 255] },
    styles: { fontSize: 8, cellPadding: 2.8, font: "helvetica" },
    margin: { left: 12, right: 12 },
  });

  // Save the report with formatted timestamp
  const reportFilename = `rapidash-report-${session.metadata.statement_timestamp.replace(/[^0-9a-zA-Z-]/g, "_")}.pdf`;
  doc.save(reportFilename);
}
